name: Convert PO to MO

on:
  push:
    paths:
      - 'nl_NL.po'  # Triggers only when nl_NL.po is modified
  workflow_dispatch:  # Allows manual triggering

jobs:
  convert-po-to-mo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install po2mo
        run: |
          curl -fsSL https://raw.githubusercontent.com/devjiwonchoi/po2mo/main/scripts/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add installation path to system PATH
          echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc  # Persist PATH
          source ~/.bashrc  # Reload shell

      - name: Verify po2mo installation
        run: |
          ls -l $HOME/.local/bin
          which po2mo || echo "po2mo not found in PATH"
          echo $PATH

      - name: Convert nl_NL.po to nl_NL.mo
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          $HOME/.local/bin/po2mo nl_NL.po nl_NL.mo  # Use full path to ensure execution

      - name: Commit and push changes
        run: |
          git config --global user.name "YOURLS PO to MO converter"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nl_NL.mo
          git commit -m "Auto-generate nl_NL.mo from nl_NL.po"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.YOURLS_POT }}
