name: Convert PO to MO

on:
  push:
    paths:
      - 'nl_NL.po' #run when .po file changes
  workflow_dispatch: #or manually run

jobs:
  convert-po-to-mo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install po2mo
        run: pip install git+https://github.com/devjiwonchoi/po2mo.git

      - name: Convert nl_NL.po to nl_NL.mo
        run: po2mo nl_NL.po nl_NL.mo

      - name: Commit and push changes
        run: |
          git config --global user.name "YOURLS PO to MO converter"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nl_NL.mo
          git commit -m "Auto-generate nl_NL.mo from nl_NL.po"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.YOURLS_POT }}
