name: Convert PO to MO

on:
  push:
    paths:
      - 'nl_NL.po'  # Triggers only when nl_NL.po is modified
  workflow_dispatch:  # Allows manual triggering

jobs:
  convert-po-to-mo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure local bin directory exists
        run: mkdir -p $HOME/.local/bin  # Ensure the directory exists before installation

      - name: Install po2mo
        run: |
          curl -fsSL https://raw.githubusercontent.com/devjiwonchoi/po2mo/main/scripts/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add installation path to system PATH

      - name: Verify po2mo installation
        run: |
          echo "Checking if po2mo is in PATH..."
          which po2mo || echo "po2mo not found in PATH"

          echo "Checking default installation directory..."
          ls -l $HOME/.local/bin || echo "Directory does not exist"

          echo "Searching entire home directory for po2mo..."
          find $HOME -name "po2mo" 2>/dev/null

      - name: Convert nl_NL.po to nl_NL.mo
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          PO2MO_PATH=$(find $HOME -name "po2mo" 2>/dev/null | head -n 1)  # Get first found path
          if [ -x "$PO2MO_PATH" ]; then
            echo "Using found po2mo at: $PO2MO_PATH"
            $PO2MO_PATH nl_NL.po nl_NL.mo
          else
            echo "po2mo not found. Exiting."
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "YOURLS PO to MO converter"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nl_NL.mo
          git commit -m "Auto-generate nl_NL.mo from nl_NL.po"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.YOURLS_POT }}
